repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.8'
    hooks:
    - id: flake8
      args: [--max-line-length=88]
-   repo: https://github.com/PyCQA/bandit
    rev: '1.6.2'
    hooks:
    - id: bandit
      entry: bandit
      args: [-x tests]
